apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: app-nginx
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: app-nginx
  template:
    metadata:
      name: nginx-pod
      labels:
        app: app-nginx
    spec:
      containers:
        - name: nginx-container
          image: library/nginx:1.25.1-alpine
          imagePullPolicy: Never
          ports:
            - containerPort: 80
