apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nginx-config
  labels:
    type: local
spec:
  capacity:
    storage: 100Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nginx-class-config
  local:
    path: /k8s-volumes/nginx/config
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
              - shermine237-latitudee6410
