apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nginx-html-3
  labels:
    type: local
spec:
  capacity:
    storage: 100Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nginx-class-html
  local:
    path: /k8s-volumes/nginx/html
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
              - shermine237-latitudee6410
